python mlpPretrain.py --flMode avg --args_key 1-1 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 2-1 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 2-2 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 3-1 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 3-2 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 4-1 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 4-2 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 4-3 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 4-4 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 4-5 --wandb_project trainOnlyOneGraph --use_wandb True
python mlpPretrain.py --flMode avg --args_key 4-6 --wandb_project trainOnlyOneGraph --use_wandb True